from .tool_agent_concierge import get_client_profile
from .tool_agent_bureau import get_bureau_consolidated
from .tool_agent_cartao import get_cartao_consolidated
from .tool_agent_contrato import get_contrato_consolidated
from .tool_agent_pagamento import get_pagamento_consolidated